version: '3.3'

services:
  postgres:
    image: postgres:13.2
    restart: always
    command: postgres -c 'max_connections=10000'
    environment:
      POSTGRES_DB: datahike
      POSTGRES_USER: datahike
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    