version: '3.3'

services:
  postgres:
    image: postgres:14
    command: postgres -p 5433
    restart: always
    environment:
      POSTGRES_DB: datahike
      POSTGRES_USER: datahike
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5433"