version: 2.1

orbs:
  tools: replikativ/clj-tools@0

jobs:
  build:
    executor: tools/clojurecli
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Build
          command: clojure -Sthreads 1 -T:build uber
          no_output_timeout: 5m
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - replikativ/target
  deploy:
    executor: tools/clojurecli
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Deploy to Docker Hub
          command: |
            clojure -Sthreads 1 \
                    -T:build deploy-image \
                    :docker-login ${DOCKER_LOGIN} \
                    :docker-password ${DOCKER_PASSWORD} \
          no_output_timeout: 5m
  release:
    executor: tools/clojurecli
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Release
          command: clojure -Sthreads 1 -T:build release

workflows:
  build-test-and-deploy:
    jobs:
      - tools/setup:
          context: dockerhub-deploy
          setup_cljs: false
      - tools/format:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/unittest:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/integrationtest:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - build:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - deploy:
          context:
            - dockerhub-deploy
          filters:
            branches:
              only: main
          requires:
            - tools/setup
            - tools/format
            - tools/unittest
            - tools/integrationtest
            - build
      - release:
          context:
            - dockerhub-deploy
            - github-token
          filters:
            branches:
              only: main
          requires:
            - deploy
